load("//cluster_controller/toolchain:flags.bzl", "CPP_FLAGS")

cc_library(
    name = "engine",
    srcs = ["engine.cpp"],
    hdrs = ["engine.hpp"],
    visibility = ["//visibility:public"],
    copts = CPP_FLAGS
)